import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    backgroundColor: "#ffffff",
    paddingHorizontal: 16,
  },
  addPostForm: {
    paddingTop: 32,
    alignItems: "center",
    justifyContent: "space-between",
  },
  addImage: {
    position: "relative",
    width: 343,
    height: 240,
    backgroundColor: "#E8E8E8",
    borderRadius: 8,
  },
  addImageBtn: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 10,
    width: 60,
    height: 60,
    top: 90,
    left: 142,
    position: "absolute",
    borderRadius: 50,
    backgroundColor: "rgba(255, 255, 255, 0.3)",
  },
  addImageBtnIcon: {},
  picture: {
    width: 343,
    height: 240,
    borderRadius: 8,
  },
  addImageText: {
    alignSelf: "flex-start",
    marginTop: 8,
    fontFamily: "Roboto-Regular",
    fontSize: 16,
    color: "#BDBDBD",
    // fontWeight: 400,
    lineHeight: 19,
    textAlign: "left",
  },
  inputWrapper: {
    marginTop: 32,
    alignSelf: "flex-start",
    width: "100%",
    height: 50,
    display: "flex",
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    gap: 4,
    borderBottomColor: "#E8E8E8",
    borderBottomWidth: 1,
  },
  input: {
    fontFamily: "Roboto-Medium",
    fontSize: 16,
    color: "#212121",
    // fontWeight: 500,
    lineHeight: 19,
    textAlign: "left",
  },
  addPostBtn: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 32,
    width: "100%",
    backgroundColor: "#FF6C00",
    borderRadius: 100,
    padding: 16,
  },
  addPostBtnText: {
    fontFamily: "Roboto-Regular",
    textAlign: "center",
    color: "#ffffff",
    fontSize: 16,
    lineHeight: 19,
  },
  removePostBtn: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: 70,
    height: 40,
    padding: 8,
    marginTop: 120,
    backgroundColor: "#FF6C00",
    borderRadius: 20,
  },

  flipContainer: {
    flex: 0.3,
    alignSelf: "flex-end",
  },

  takePhotoOut: {
    borderWidth: 2,
    borderColor: "white",
    height: 50,
    width: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 50,
  },

  takePhotoInner: {
    borderWidth: 2,
    borderColor: "white",
    height: 40,
    width: 40,
    backgroundColor: "black",
    borderRadius: 50,
  },
});
