import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    backgroundColor: "#ecf0f1",
  },
  bgImage: {
    flex: 1,
    justifyContent: "flex-end",
  },
  contentBox: {
    maxHeight: "70%",
    position: "relative",
    justifyContent: "flex-start",
    backgroundColor: "#ffffff",
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    paddingTop: 32,
    paddingHorizontal: 16,
    paddingBottom: 153,
  },
  title: {
    fontFamily: "Roboto-Medium",
    fontSize: 30,
    color: "#212121",
    fontWeight: 500,
    lineHeight: 35,
    textAlign: "center",
    letterSpacing: 0.01,
    marginBottom: 32,
  },
  avatarWrapper: {
    position: "relative",
    alignSelf: "center",
    marginTop: -92,
    marginBottom: 32,
    backgroundColor: "#F6F6F6",
    borderRadius: 16,
    width: 120,
    height: 120,
  },
  avatar: {
    borderRadius: 16,
    width: 120,
    height: 120,
  },
  logoutBtn: {
    position: "absolute",
    top: 22,
    right: 18,
  },
  postsList: {},
  postsListItem: {
    marginBottom: 32,
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  postImage: {
    width: "100%",
    height: 240,
    borderRadius: 8,
    alignSelf: "center",
  },
  postText: {
    fontFamily: "Roboto-Medium",
    fontSize: 16,
    color: "#212121",
    fontWeight: 500,
    lineHeight: 19,
  },
  postDataWrapper: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  postDataCommentsWrapper: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 6,
  },
  postComments: {
    fontFamily: "Roboto-Regular",
    fontSize: 16,
    color: "#212121",
    fontWeight: 400,
    lineHeight: 19,
  },
  postLocationWrapper: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 6,
  },
  postLocation: {
    fontFamily: "Roboto-Regular",
    fontSize: 16,
    color: "#212121",
    fontWeight: 400,
    lineHeight: 19,
    textDecorationLine: "underline",
  },
  postDataAchievesWrapper: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 24,
  },
});
